// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> addOverlay(
        {required List<int> background,
        required (
          Uint8List,
          PlatformInt64?,
          PlatformInt64?,
          int?,
          int?
        ) texture}) =>
    RustLib.instance.api
        .crateApiSimpleAddOverlay(background: background, texture: texture);
